@BASE_URL=http://localhost:8080/pessoa

### Obter uma pessoa
GET {{BASE_URL}}/1

### Obter todas as pessoas
GET {{BASE_URL}}

### Criar pessoa
POST {{BASE_URL}}
Content-Type: application/json

{
  "nome": "Jailson",
  "email": "jailson@gmail.com",
  "senha": "123456"
}

### Atualizar pessoa
PUT {{BASE_URL}}/1
Content-Type: application/json

{
  "nome": "Jailson",
  "email": "jailsonmendes@gmail.com"
}

### Atualizar pessoa e senha
PUT {{BASE_URL}}/1
Content-Type: application/json

{
  "nome": "Jailson",
  "email": "jailsonmendes@gmail.com",
  "senhaAntiga": "123456",
  "senhaNova": "654321"
}

### Deletar pessoa
DELETE {{BASE_URL}}/1
Content-Type: application/json

{
  "email": "jailsonmendes@gmail.com",
  "senha": "654321"
}